function turtleDigging()
    for i = 1, 3 do
        turtle.dig()
        turtle.forward()
        turtle.dig()
        turtle.forward()
        turtle.dig()
        turtle.forward()
        turtle.dig()
        turtle.forward()
        turtle.turnLeft()
        turtle.turnLeft()
        turtle.digUp()
        turtle.up()
        turtle.dig()
        turtle.forward()
        turtle.dig()
        turtle.forward()
        turtle.dig()
        turtle.forward()
        turtle.dig()
        turtle.forward()
        turtle.turnRight()
        turtle.turnRight()
        turtle.digUp()
        turtle.up()
    end
end

turtle.select(1)
turtle.equipLeft()
turtle.select(2)
turtle.equipRight()
turtle.select(1)
local modem = peripheral.find("modem", rednet.open)
local id, message, protocol = rednet.receive()
print(message)
if message == "tunnel" then
    rednet.send(1, "For how long?")
end

message = 0;
local id, message, protocol = rednet.receive()
message = tonumber(message)
if message ~= 0 then
    for i = 1, message do
        turtle.dig()
        turtle.forward()
        turtle.turnRight()
        turtleDigging()
        turtle.turnRight()
        turtle.turnRight()
        turtle.forward()
        turtle.digUp()
        turtle.up()
        turtle.dig()
        turtle.forward()
        turtle.dig()
        turtle.forward()
        turtle.turnLeft()
        turtle.turnLeft()
        turtle.down()
        turtle.down()
        turtle.down()
        turtle.down()
        turtle.down()
        turtle.down()
        turtle.forward()
        turtle.forward()
        turtle.forward()
        turtle.turnRight()
    end
end
